name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
    
    - name: Set VCPKG_ROOT environment variable
      run: |
        echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $env:GITHUB_ENV

    - name: Install dependencies with vcpkg
      run: |
        .\vcpkg\vcpkg.exe install --recurse --clean-after-build

    - name: Configure with CMakePresets
      run: cmake --preset=default

    - name: Build with CMakePresets
      run: cmake --build --preset=default

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
          name: windows-x86-build
          path: ${{ github.workspace }}/build/Release